use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMKeywordVCManager_Example' do
  pod 'AHFMKeywordVCManager', :path => '../'

  target 'AHFMKeywordVCManager_Tests' do
    inherit! :search_paths

    
  end
end
